"""Test-1: fixture-replay byte-comparison for scripts/init.sh.

Per F-248 §Regression Protection Plan, this test runs init.sh in a tmpdir
clone with the canonical fixture inputs (matching tests/fixtures/regenerate-
baseline.sh) and walks the resulting personalized tree, asserting each file's
bytes equal the recorded baseline at tests/fixtures/init-baseline-tree/.

The baseline tree is generated by `tests/fixtures/regenerate-baseline.sh`
(T013) AFTER the Stream 1 substitution adoption lands (T014). Until that
runs, the baseline directory is empty and the test xfails with a clear
reason — it cannot pass without the post-Stream-1 baseline.

Test-first per Constitution VI: this file lands BEFORE T015–T021. When run
against pre-merge baseline, the test xfails because the baseline is absent.
Post-Stream-1 + T014, it should pass green on macOS bash 3.2.57 + ubuntu
bash 5.x.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from init_sh_helpers import (
    build_canonical_stdin,
    clone_into_tmpdir,
    files_in_tree,
    run_init_in_clone,
)

BASELINE_DIR = Path(__file__).resolve().parents[1] / "fixtures" / "init-baseline-tree"


@pytest.fixture(scope="module")
def init_run(tmp_path_factory: pytest.TempPathFactory):
    """Module-scoped: run init.sh once with canonical inputs in a tmpdir clone."""
    tmpdir = tmp_path_factory.mktemp("init_sh_substitution")
    clone_root = clone_into_tmpdir(tmpdir)
    stdin_payload = build_canonical_stdin(clone_root)
    result = run_init_in_clone(clone_root, stdin_payload)
    if result.returncode != 0:
        pytest.fail(
            f"init.sh exited {result.returncode}; "
            f"stderr last lines:\n{result.stderr[-1500:]}"
        )
    return result


@pytest.mark.skipif(
    not BASELINE_DIR.is_dir() or not any(BASELINE_DIR.iterdir()),
    reason=(
        "tests/fixtures/init-baseline-tree/ not yet regenerated; "
        "run tests/fixtures/regenerate-baseline.sh after Stream 1 (T014)"
    ),
)
def test_personalized_tree_bytes_match_baseline(init_run):
    """Every file in the personalized tree byte-equals the recorded baseline,
    EXCEPT files known to contain non-deterministic content (timestamps, the
    clone HEAD SHA captured by init.sh).

    Drift exclusions:
    - `.aod/aod-kit-version`: contains `updated_at` (UTC second-precision
      timestamp) and `sha` (cloned HEAD SHA). Both legitimately differ between
      the moment T014 regenerated the baseline and any subsequent test run.
      File-mode parity is still asserted in the modes test below.
    """
    clone_root = init_run.tmpdir
    actual_files = files_in_tree(clone_root)
    baseline_files = files_in_tree(BASELINE_DIR)

    # File set parity: actual ≈ baseline (modulo init.sh self-delete which is
    # tested separately; the baseline already reflects post-init state).
    assert set(actual_files) == set(baseline_files), (
        f"file set drift:\n"
        f"  in actual but not baseline: {sorted(set(actual_files) - set(baseline_files))[:20]}\n"
        f"  in baseline but not actual: {sorted(set(baseline_files) - set(actual_files))[:20]}"
    )

    DRIFT_ALLOWED = {Path(".aod/aod-kit-version")}
    mismatches: list[str] = []
    for rel in actual_files:
        if rel in DRIFT_ALLOWED:
            continue
        actual_bytes = (clone_root / rel).read_bytes()
        baseline_bytes = (BASELINE_DIR / rel).read_bytes()
        if actual_bytes != baseline_bytes:
            mismatches.append(str(rel))
    assert not mismatches, (
        f"{len(mismatches)} file(s) drifted from baseline. First 10: {mismatches[:10]}"
    )


@pytest.mark.skipif(
    not BASELINE_DIR.is_dir() or not any(BASELINE_DIR.iterdir()),
    reason="baseline not yet regenerated (see test above)",
)
def test_personalized_tree_modes_match_baseline(init_run):
    """File-mode bits (executable bit) are preserved by the substitution loop."""
    clone_root = init_run.tmpdir
    drifts: list[str] = []
    for rel in files_in_tree(clone_root):
        baseline_path = BASELINE_DIR / rel
        if not baseline_path.is_file():
            continue
        actual_mode = (clone_root / rel).stat().st_mode & 0o777
        baseline_mode = baseline_path.stat().st_mode & 0o777
        if actual_mode != baseline_mode:
            drifts.append(f"{rel}: {oct(actual_mode)} vs baseline {oct(baseline_mode)}")
    assert not drifts, f"mode drift on {len(drifts)} file(s): {drifts[:5]}"
