// =============================================================================
// Report Configuration: Security Assessment PDF Booklet
// =============================================================================
// User-configurable overrides for report generation. Edit this file to
// customize the report without modifying any template files.
//
// The report assembler copies a user-provided report-config.typ from the
// target directory into templates/tachi/security-report/ before compilation.
// If no user config exists, this default file is used.
//
// Variables:
//   show-disclaimer       — boolean; include the disclaimer page (default: true)
//   show-methodology      — boolean; include the methodology page (default: true)
//   custom-disclaimer-text — string or none; replaces default disclaimer sections
//   custom-footer-text     — string or none; replaces "Generated by tachi" footer
// =============================================================================


// ---------------------------------------------------------------------------
// Page Visibility
// ---------------------------------------------------------------------------

/// Include the legal disclaimer page (page 2).
#let show-disclaimer = true

/// Include the risk methodology page (page 4).
#let show-methodology = true


// ---------------------------------------------------------------------------
// Custom Text Overrides
// ---------------------------------------------------------------------------

/// Custom disclaimer content. When not none, replaces all four default
/// notice sections on the disclaimer page.
#let custom-disclaimer-text = none

/// Custom footer text. When not none, replaces "Generated by tachi" in the
/// page footer across all text pages.
#let custom-footer-text = none
