"""Shared helpers for the F-248 init.sh pytest-via-subprocess suite.

Used by:
- test_init_sh_substitution.py (Test-1 fixture-replay byte-comparison)
- test_init_sh_adversarial.py (Test-2 ≥13 adversarial inputs)
- test_init_sh_constitution.py (Test-4 byte-compare)
- test_init_sh_self_delete.py (Test-5' self-delete preservation)

Not collected as a test module (filename does not start with `test_`).
"""

from __future__ import annotations

import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


@dataclass(frozen=True)
class InitRun:
    returncode: int
    stdout: str
    stderr: str
    tmpdir: Path


# Canonical fixture inputs — match T008 baseline benchmark and quickstart.md
# §Performance Sanity Check. PROJECT_NAME=tachi anchors the byte-comparison
# baseline tree generated by tests/fixtures/regenerate-baseline.sh (T013).
CANONICAL_INPUTS: list[str] = [
    "tachi",                      # PROJECT_NAME
    "threat modeling sidecar",    # PROJECT_DESCRIPTION
    "benchmark-test-org",         # GITHUB_ORG (non-real to avoid gh side effects)
    "",                           # GITHUB_REPO (empty → defaults to PROJECT_NAME)
    "1",                          # AI agent: Claude Code
    # Stack pack choice and tech stack inputs are appended dynamically based
    # on how many stack packs the repo contains at run time. See
    # build_canonical_stdin() below.
]


def discover_pack_count(clone_root: Path) -> int:
    """Count stack packs that have a STACK.md (matches init.sh discovery).

    init.sh iterates `stacks/*/` and only counts dirs with STACK.md present.
    The "Other / Not yet defined" choice is at index = count + 1.
    """
    stacks_dir = clone_root / "stacks"
    if not stacks_dir.is_dir():
        return 0
    return sum(1 for d in stacks_dir.iterdir() if (d / "STACK.md").is_file())


def build_canonical_stdin(clone_root: Path, project_name: str = "tachi",
                          project_description: str = "threat modeling sidecar",
                          github_org: str = "benchmark-test-org",
                          github_repo: str = "",
                          tech_stack: str = "Python + FastAPI",
                          tech_stack_database: str = "PostgreSQL",
                          cloud_provider: str = "") -> str:
    """Assemble the stdin sequence for a non-interactive init.sh run.

    Choosing "Other" for stack pack keeps the test independent of which
    packs ship in the repo. Returns a newline-terminated single string
    suitable for `subprocess.run(input=...)`.
    """
    pack_count = discover_pack_count(clone_root)
    other_index = pack_count + 1
    lines = [
        project_name,
        project_description,
        github_org,
        github_repo,
        "1",                  # AI agent: Claude Code
        str(other_index),     # Stack: Other
        tech_stack,
        tech_stack_database,
        cloud_provider,
        "Y",                  # Confirm
    ]
    return "\n".join(lines) + "\n"


def clone_into_tmpdir(tmpdir: Path) -> Path:
    """Clone the repo's CURRENT HEAD into <tmpdir>/tachi via local file://.

    Resolves the source repo's HEAD SHA via `git rev-parse HEAD` and
    explicitly checks it out in the clone. This makes the test:
    - reproducible (clone state matches the committed state at HEAD,
      regardless of uncommitted working-tree changes)
    - branch-aware (Wave 3+ implementations on the feature branch are
      visible to tests as soon as their commits land)

    Returns the clone root path.
    """
    head_sha = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()

    clone_root = tmpdir / "tachi"
    subprocess.run(
        ["git", "clone", "--quiet", f"file://{REPO_ROOT}", str(clone_root)],
        check=True,
        capture_output=True,
    )
    subprocess.run(
        ["git", "checkout", "--quiet", head_sha],
        cwd=str(clone_root),
        check=True,
        capture_output=True,
    )
    return clone_root


def run_init_in_clone(clone_root: Path, stdin_payload: str,
                      timeout_sec: int = 300) -> InitRun:
    """Invoke `bash ./scripts/init.sh` inside <clone_root> non-interactively.

    Sets LC_ALL=C (matches T008 baseline) and HOME=<isolated tmpdir> so
    `gh auth status` in init.sh detects no auth and BOARD_STATUS skips
    network calls. Returns InitRun with captured streams + return code.
    """
    fake_home = clone_root.parent / "fake_home"
    fake_home.mkdir(exist_ok=True)
    env = {
        **os.environ,
        "LC_ALL": "C",
        "HOME": str(fake_home),
        # Strip any inherited PATH that would surface gh; rely on /usr/bin
        # + /bin for git/node/bash. Tests run on dev macs and CI runners
        # which both have those in /usr/bin or /bin.
        "PATH": _safe_path(),
        # Pin the dates that init.sh substitutes into RATIFICATION_DATE +
        # CURRENT_DATE so the personalized tree is byte-deterministic across
        # runners (Test-1 fixture-replay byte-comparison would otherwise
        # false-fail on CI/dev TZ skew — e.g., dev EDT shows 2026-05-03 while
        # ubuntu UTC shows 2026-05-04 for the same wall-clock instant).
        # The override ENV vars are read by scripts/init.sh as
        # `${AOD_*_OVERRIDE:-$(date +%Y-%m-%d)}` so production runs are
        # unaffected (no override set → live date).
        "AOD_RATIFICATION_DATE_OVERRIDE": "2026-05-04",
        "AOD_CURRENT_DATE_OVERRIDE": "2026-05-04",
    }
    completed = subprocess.run(
        ["bash", "./scripts/init.sh"],
        cwd=str(clone_root),
        input=stdin_payload,
        capture_output=True,
        text=True,
        env=env,
        timeout=timeout_sec,
    )
    return InitRun(
        returncode=completed.returncode,
        stdout=completed.stdout,
        stderr=completed.stderr,
        tmpdir=clone_root,
    )


def _safe_path() -> str:
    """PATH minus directories that commonly contain `gh`.

    Filters /opt/homebrew/bin, /usr/local/bin (Homebrew defaults). Keeps
    /usr/bin and /bin so git/bash/node remain available. node is usually
    in /usr/local/bin or /opt/homebrew/bin — if it cannot be found, we
    fall back to keeping the original PATH but warn callers via stderr
    by deferring the gh isolation to HOME-based auth-state suppression.
    """
    blocked = {"/opt/homebrew/bin", "/usr/local/bin", "/opt/homebrew/sbin"}
    parts = os.environ.get("PATH", "").split(":")
    kept = [p for p in parts if p not in blocked]
    # Validate node is still reachable; if not, retain original PATH and
    # rely on isolated HOME for gh-auth suppression.
    has_node = any((Path(p) / "node").exists() for p in kept if p)
    if not has_node:
        return os.environ.get("PATH", "")
    return ":".join(kept)


def files_in_tree(root: Path, *, include_dotfiles: bool = True) -> list[Path]:
    """Yield regular files under <root>, mirroring init.sh find filter.

    Excludes:
    - .git/, node_modules/
    - *.png, *.jpg, *.ico
    - tests/fixtures/init-baseline-tree/ (the baseline path itself — when
      walking a live clone this directory contains the previously-committed
      baseline as committed-tree content, not post-init substituted output;
      including it would double-count the baseline on the "actual" side and
      cause spurious file-set drift)

    Returns paths relative to <root> for stable byte-comparison.
    """
    excluded_dirs = {".git", "node_modules"}
    excluded_suffixes = {".png", ".jpg", ".ico"}
    excluded_path_prefix = Path("tests") / "fixtures" / "init-baseline-tree"
    out: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(root)
        if any(part in excluded_dirs for part in rel.parts):
            continue
        if path.suffix in excluded_suffixes:
            continue
        try:
            rel.relative_to(excluded_path_prefix)
            continue
        except ValueError:
            pass
        out.append(rel)
    return sorted(out)


def cleanup(path: Path) -> None:
    """Best-effort recursive remove. Used by fixtures with `addfinalizer`."""
    if path.exists():
        shutil.rmtree(path, ignore_errors=True)
