"""Test-1: fixture-replay byte-comparison for scripts/init.sh.

Per F-248 §Regression Protection Plan, this test runs init.sh in a tmpdir
clone with the canonical fixture inputs (matching tests/fixtures/regenerate-
baseline.sh) and walks the resulting personalized tree, asserting each file's
bytes equal the recorded baseline at tests/fixtures/init-baseline-tree/.

The baseline tree is generated by `tests/fixtures/regenerate-baseline.sh`
(T013) AFTER the Stream 1 substitution adoption lands (T014). Until that
runs, the baseline directory is empty and the test xfails with a clear
reason — it cannot pass without the post-Stream-1 baseline.

Test-first per Constitution VI: this file lands BEFORE T015–T021. When run
against pre-merge baseline, the test xfails because the baseline is absent.
Post-Stream-1 + T014, it should pass green on macOS bash 3.2.57 + ubuntu
bash 5.x.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from init_sh_helpers import files_in_tree

BASELINE_DIR = Path(__file__).resolve().parents[1] / "fixtures" / "init-baseline-tree"

# `init_run` is provided by conftest.py at session scope — one canonical
# init.sh invocation is shared across all test_init_sh_* modules to avoid
# multiplying the macos cold-cache cost (workflow comment in tachi-pytest.yml
# notes macos-latest is 3-4x slower than dev hardware on init.sh cold runs).


@pytest.mark.skipif(
    not BASELINE_DIR.is_dir() or not any(BASELINE_DIR.iterdir()),
    reason=(
        "tests/fixtures/init-baseline-tree/ not yet regenerated; "
        "run tests/fixtures/regenerate-baseline.sh after Stream 1 (T014)"
    ),
)
def test_personalized_tree_bytes_match_baseline(init_run):
    """Every file in the personalized tree byte-equals the recorded baseline,
    EXCEPT files known to contain non-deterministic content (timestamps, the
    clone HEAD SHA captured by init.sh).

    Drift exclusions:
    - `.aod/aod-kit-version`: contains `updated_at` (UTC second-precision
      timestamp) and `sha` (cloned HEAD SHA). Both legitimately differ between
      the moment T014 regenerated the baseline and any subsequent test run.
      File-mode parity is still asserted in the modes test below.
    """
    clone_root = init_run.tmpdir
    actual_set = set(files_in_tree(clone_root))
    baseline_set = set(files_in_tree(BASELINE_DIR))

    # SUBSTITUTION-DROP CONTRACT (regression signal):
    # init.sh produced fewer files than the baseline expects. This is the
    # real regression path the test exists to catch — substitution loop
    # silently skipping a file or self-delete sweeping too aggressively.
    missing_from_actual = baseline_set - actual_set
    assert not missing_from_actual, (
        f"init.sh dropped {len(missing_from_actual)} file(s) from the "
        f"personalized tree (substitution regression suspected). First 10:\n  "
        + "\n  ".join(str(p) for p in sorted(missing_from_actual)[:10])
    )

    # REPO-GROWTH TOLERANCE (NOT a substitution regression):
    # Files present in actual but absent from baseline mean the repo grew
    # since `tests/fixtures/regenerate-baseline.sh` was last run. Adopters
    # receive these files via init.sh on every install — they're outside
    # the byte-comparison contract. Maintainers can refresh the baseline
    # at their discretion; the test does not block PRs that add files.

    # BYTE-CONTENT CONTRACT:
    # Files present in BOTH sets must match exactly. This catches genuine
    # substitution-semantics drift (e.g., a `&` corruption regressing the
    # F-248 fix, or a `LC_ALL` regression mangling multibyte boundaries).
    DRIFT_ALLOWED = {Path(".aod/aod-kit-version")}
    mismatches: list[str] = []
    for rel in (actual_set & baseline_set):
        if rel in DRIFT_ALLOWED:
            continue
        actual_bytes = (clone_root / rel).read_bytes()
        baseline_bytes = (BASELINE_DIR / rel).read_bytes()
        if actual_bytes != baseline_bytes:
            mismatches.append(str(rel))
    assert not mismatches, (
        f"{len(mismatches)} file(s) drifted from baseline. First 10: {mismatches[:10]}"
    )


@pytest.mark.skipif(
    not BASELINE_DIR.is_dir() or not any(BASELINE_DIR.iterdir()),
    reason="baseline not yet regenerated (see test above)",
)
def test_personalized_tree_modes_match_baseline(init_run):
    """File-mode bits (executable bit) are preserved by the substitution loop."""
    clone_root = init_run.tmpdir
    drifts: list[str] = []
    for rel in files_in_tree(clone_root):
        baseline_path = BASELINE_DIR / rel
        if not baseline_path.is_file():
            continue
        actual_mode = (clone_root / rel).stat().st_mode & 0o777
        baseline_mode = baseline_path.stat().st_mode & 0o777
        if actual_mode != baseline_mode:
            drifts.append(f"{rel}: {oct(actual_mode)} vs baseline {oct(baseline_mode)}")
    assert not drifts, f"mode drift on {len(drifts)} file(s): {drifts[:5]}"
